version: "3"
services:
  app:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    restart: "no"
    ports:
      - 8080:8080
    volumes:
      - ./api/src:/app/src
    command: ["npm", "run", "dev"]

